package myData;
// Generated 3 May, 2023 8:01:46 PM by Hibernate Tools 4.3.1



/**
 * Userdata generated by hbm2java
 */
public class Userdata  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String lname;
     private String city;
     private String branch;

    public Userdata() {
    }

    public Userdata(String fname, String lname, String city, String branch) {
       this.fname = fname;
       this.lname = lname;
       this.city = city;
       this.branch = branch;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }




}


